GLUE-228-마이페이지구현
DoTheZ-Team/glue-fe pull request #12
Opened 2024-04-23 05:28 UTC by yeyounging

파트별로 컴포넌트 구현

## 1. 무슨 이유로 코드를 변경했나요?

<br> 마이페이지를 구현했습니다.

## 2. 어떤 위험이나 장애를 발견했나요?

<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>
<img width="1512" alt="image" src="https://github.com/DoTheZ-Team/glue-fe/assets/133792082/7eb6df65-b715-43c1-8491-19ceb9454681">
<img width="1510" alt="image" src="https://github.com/DoTheZ-Team/glue-fe/assets/133792082/252f9a0f-4d5e-476c-90b3-a40814dbe9ff">
<img width="1512" alt="image" src="https://github.com/DoTheZ-Team/glue-fe/assets/133792082/81a9b2d6-9c19-4ac2-b319-1834be0bfdee">
![Uploading image.png…]()

## 4. 완료 사항

<br> 사용자 id 를 파라미터로 받아서 프로필, 배경 기본값 설정
<br> <close>버튼으로 사진 삭제 기능
<br> 사용자 사진 업로드 및 썸네일 기능 

## 5. 추가 사항

<br> s3와 연결해야합니다.

2024-04-23 14:49 UTC, Collection50 requested changes
고생하셨습니다 !

코드에 관해 코멘트 남겼습니다.

커밋 메시지가 올바르게 지켜지지 않는 것 같아요.
[여기](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit?pli=1#heading=h.uyo6cb12dt6w) 참조해서 지켜주시면 좋을 것 같습니다 👍

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/FileEdit/FileThumbnails.tsx
> +        <div className={`relative ${containerSize} border border-[#afacac] `}>
util 함수 cn을 사용하는게 좋을 것 같아요.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/FileEdit/index.tsx
> +    <div className="">
className이 필요없어 보입니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/FileEdit/index.tsx
> +        style={{ display: 'none' }}
인라인 스타일을 사용하기보다 className을 사용하는 것을 권장합니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/FileEdit/index.tsx
> +  setFile: React.Dispatch<React.SetStateAction<File | null>>;
React를 사용하기 보다 각각의 Dispatch, SetStateAction를 선언해서 사용하는 것을 권장드립니다. 아래의 코드 모두에 적용하시면 좋을 것 같아요.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/FileEdit/index.tsx
> +    }
```suggestion
    if (inputEl.files?.[0]) {
      setFile(selectedFile);
    }
```

위와같은 사용법이 더 좋아보입니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/profile/index.tsx
> +  const handleNameChange = (e) => {
이벤트 핸들러에 타입 할당이 필요합니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/page.tsx
> +    </main>
mypage/layout.tsx에 main 태그가 존재하므로 여기에는 없어도 될 것 같아요.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/Title/index.tsx
> +    </article>
title로 작용하는 곳이므로 article보다 header 태그가 더 좋아보이는데 어떻게 생각하시나요?

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/Title/index.tsx
> +        <Underline className="absolute bottom-2 w-500" />
```suggestion
      <div className="relative text-center">
        <p>playground</p>
        <Underline className="absolute bottom-2 w-500" />
```

Underline이 absolute로 포지셔닝되고 있으므로 위와 같은 코드도 정상 작동할 것 같아요.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/FileEdit/FileThumbnails.tsx
> +  deleteFileHandler?: () => void;
```suggestion
  deleteFileHandler: () => void;
```

deleteFileHandler는 필수적으로 사용되고 있고, 사용될 것 같아요.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/FileEdit/FileThumbnails.tsx
> +        <div className={`relative ${containerSize} border border-[#afacac] `}>
그렇다면 위의 containerSize 변수를 따로 선언하지 않아도 됩니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/lib/dummyData.js
> +  return user ? user.background : null;
```js
const { background } = users.find(({ id }) => id === userId);
return background || null;
```

위와 같은 코드로 리팩토링할 수 있겠어요. users를 순회하고 있으므로 mem이라는 변수명보다 user가 더 좋을 것 같고 구조분해를 추가했어요.

위의 getProfileImageById 함수도 동일하게 리팩토링할 수 있습니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/Background/index.tsx
> +  }, [id]);
동일한 로직이 `src/app/mypage/components/profile/index.tsx`에서도 사용되고 있어요.
이 경우 custom hook으로 분리하는 것이 재사용 측면에서 좋을 것 같아요.

또한 비즈니스 로직과 view를 나누는 관점에서도 더 좋을 것 같습니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/BlogName/index.tsx
> +        />
input 태그를 사용하는 경우 Input 컴포넌트를 사용하는 것이 좋을 것 같아요.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/BlogName/index.tsx
> +        />
위와 동일합니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/FileEdit/index.tsx
> +        style={{ display: 'none' }}
input 태그를 사용하는 경우 Input 컴포넌트를 사용하는 것을 권장드립니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/profile/index.tsx
> +            className="border border-primary/70 p-10 rounded-md w-250 h-30"
input 태그를 사용하는 경우 Input 컴포넌트를 사용하는 것을 권장드립니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/Background/index.tsx
> +export default function Background({ id }: { id: number }) {
id를 주입받아서 로직을 처리하고 있는데 불필요한 로직으로 보여요.

실제 api가 주어졌을때 각 유저의 고유성을 확인하는 것은 accessToken, refreshToken입니다.
이는 쿠키에서 관리되므로 id를 외부에서 주입받는 방식은 실제 구현과 거리가 있어보입니다.

아직 토큰, 쿠키와 관련된 처리를 할 수 없지만 id 관련 로직은 삭제하는 것이 혼란을 줄일 수 있을 것 같아요.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/profile/index.tsx
컴포넌트명은 파스칼 케이스로 작성되어야 합니다.

2024-04-23 14:49 UTC, Collection50 commented on src/app/lib/dummyData.js
> +  return user ? user.background : null;
dummyData에서만 사용되는 것이 아니라 추후 사용 예정인 경우 utils로 분리하는 것이 더 좋을 것 같아요.

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/FileEdit/FileThumbnails.tsx
> +            >
onClick 이벤트 핸들러를 사용하는 경우 div 태그보다 button 태그를 사용해야 합니다

2024-04-23 14:49 UTC, Collection50 commented on src/app/mypage/components/FileEdit/FileThumbnails.tsx
> +import React from 'react';
불필요한 import 입니다.

2024-04-24 08:39 UTC, Collection50 requested changes
고생하셨습니다 !

추가 작업에 대해 리뷰 남겨드렸습니다.

이전 리뷰에 대한 수정 요청이 모두 적용된 것은 아닌 것처럼 보입니다 ! (파일 관련 로직 hook 분리 등)

추가 작업을 통해 반영하시면 좋을 것 같아요 👍

2024-04-24 08:39 UTC, Collection50 commented on src/app/search/components/SearchBox/index.tsx
> +        />
이곳에도 Input 컴포넌트를 사용하는 것을 권장드립니다

2024-04-24 08:39 UTC, Collection50 commented on src/app/search/components/SearchBox/index.tsx
> +            rounded-2xl gap-15 p-10 border"
이렇게 줄바꿈을 해서 작성하는 것은 좋은 방법이 아닌것 같아요. 자바스크립트에서는 백틱을 제외한 따옴표에서는 줄바꿈을 허용하지 않고 있습니다.

2024-04-24 08:39 UTC, Collection50 commented on src/app/search/components/SearchBox/index.tsx
> +        <Search />
이 Search Icon에는 이벤트 핸들러가 없어서 버튼을 눌러도 검색이 되지 않을 것 같아요. UX에 좋지 않은 것 같아요.

아직 이벤트 핸들러, API 가 부착되지 않아서 작성하신 걸까요?

2024-04-28 07:07 UTC, yeyounging commented on src/app/mypage/components/Title/index.tsx
> +        <Underline className="absolute bottom-2 w-500" />
글씨와 underline이 가운데 정렬되려면 flex-col 이 있어야 정렬되는 것 같습니다. justify-center는 불필요하여 삭제했습니다!

2024-04-28 12:49 UTC, Collection50 commented on src/app/mypage/components/Common/useDefaultFile.tsx
> +  fileType: string,
fileName, fileTeyp

2024-04-28 13:05 UTC, Collection50 requested changes
고생하셨습니다 !

변경된 코드에 대해 몇가지 코멘트 남겨드렸습니다 👍

2024-04-28 13:05 UTC, Collection50 commented on src/app/mypage/components/Common/useDefaultFile.tsx
> +  }, [getDefaultFile, fileName, fileType]);
파일을 fetch하는 부분은 추후 백엔드 로직에 의해 변경될 가능성이 높습니다.
인지하고 계시면 좋을 것 같습니다 👍

2024-04-28 13:05 UTC, Collection50 commented on src/app/mypage/components/profile/index.tsx
> +    'image/png',
위 리뷰에 따라 fileName, fileType은 사용되지 않을 가능성이 높습니다.
보통 백엔드 DB의 칼럼으로 관리되기 때문입니다.

2024-04-28 13:05 UTC, Collection50 commented on src/app/mypage/components/Common/useDefaultFile.tsx
> +  getDefaultFile: string,
이 변수는 함수로 사용되는 것이 아니므로 동사 => 명사형으로 작성하시면 좋을것 같아요. fileSrc와 같은 변수명이 더 좋을 것 같아요.

2024-04-28 13:05 UTC, Collection50 commented on src/app/mypage/components/Common/useDefaultFile.tsx
> +    const defaultUrl = getDefaultFile;
새로운 변수로 선언할 필요가 없을 것 같아요. 매개변수로 받은 값을 그대로 사용하면 좋을 것 같아요.

2024-04-28 16:17 UTC, yeyounging commented on src/app/mypage/components/Common/useDefaultFile.tsx
> +  }, [getDefaultFile, fileName, fileType]);
> 파일을 fetch하는 부분은 추후 백엔드 로직에 의해 변경될 가능성이 높습니다. 인지하고 계시면 좋을 것 같습니다 👍

시연 영상때문에 일단 저장되어있는 이미지 불러오는걸로 설정해놓았습니다!

2024-04-29 00:18 UTC, Collection50 requested changes
코드 변경에 대해 새롭게 코멘트 남겼습니다~!

2024-04-29 00:18 UTC, Collection50 commented on src/app/mypage/components/Background/index.tsx
> +  const [backgroundFile, setBackgroundFile] = FileSrc(
FileSrc를 사용하라는 이전 리뷰는 useDefaultFile의 1번째 매개변수에 대한 의미였습니다~!

hook은 `use`~로 시작해야 하므로 `useReadFile`과 같은 hook 네이밍이 좋을 것 같아요.

2024-04-29 03:45 UTC, Collection50 approved these changes

2024-04-29 03:47 UTC, merged