GLUE-223-구독-api-연결
DoTheZ-Team/glue-fe pull request #37
Opened 2024-05-23 02:59 UTC by yeyounging

## 1. 무슨 이유로 코드를 변경했나요?

<br> 구독페이지에서 팔로우 api, 팔로워 api 를 연결하여 구독리스트를 구현했습니다.
#30 

## 2. 어떤 위험이나 장애를 발견했나요?

<br> 구독 리스트의 데이터 loading이 오래 걸립니다. 

## 3. 관련 스크린샷을 첨부해주세요.

<br> 
![image](https://github.com/DoTheZ-Team/glue-fe/assets/133792082/23f013fe-739d-4282-b388-9119ac4e3645)

## 4. 완료 사항

- [x]` Pagination `컴포넌트 구현
- [x] 팔로워 리스트 `FollowerListContent` 컴포넌트 구현
- [x] 팔로우 리스트  `FollowListContent` 컴포넌트 구현 

## 5. 추가 사항

- 사전 구현된 페이지네이션 컴포넌트로 변경 예정입니다.
- 변경된 구독 피드 api 반영하여 구현 예정입니다.

2024-05-23 06:43 UTC, Collection50 requested changes
고생하셨습니다 !

코드에 관해 리뷰 남겨드렸습니다 ! 👍

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/components/Feed/index.tsx
> +  }
에러의 경우 `tanstack-query`가 가까운 `ErrorBoundary`로 throw 하므로 필요 없을 것 같은데 type 에러 때문에 이렇게 하시는 건가요??

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/components/Pagination/index.tsx
이 PR 머지 후에 페이지네이션은 #36 PR 참조하셔서 변경하시면 좋을 것 같습니다 !!

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/components/Subscription/index.tsx
> +            'bg-white rounded-30 p-6 text-[12px] transition-all duration-100',
조건문이 없는 경우 문자열의 경우엔 합쳐주세요.
```suggestion
            selectedButton === '내가구독' && 'border-primary',
            'border bg-white rounded-30 p-6 text-[12px] transition-all duration-100',
```

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/components/Subscription/index.tsx
> +            'bg-white rounded-30 p-6 text-[12px] transition-all duration-100',
위 리뷰와 같습니다.

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/page.tsx
> +// import Feed from './components/Feed';
불필요한 주석으로 보입니다.

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/page.tsx
> +      {/* <Feed /> */}
불필요한 주석으로 보입니다.

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/components/SubscriptionFallback/index.tsx
이 폴더는 `Subscription` 폴더 내부로 이동하면 좋을 것 같아요.

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/components/SubscribeFetcher/index.tsx
`SubscriptionFetcher` 폴더 자체가 `Subscription` 폴더 내부로 이동하면 좋을 것 같아요.

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/components/Feed/index.tsx
> +        <p className="w-270 h-2 bg-primary mb-2" />
`p` 태그는 글에 사용되는 태그입니다.
빈 태그가 필요하다면 `p` 태그보다 `div`를 사용하는 것이 좋아보입니다.

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/components/Feed/index.tsx
2개 컴포넌트에 비즈니스 로직이 존재하므로 컴포넌트를 분리하는 것이 더 좋을 것 같아요.

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/components/SubscribeFetcher/index.tsx
> +}: StrictPropsWithChildren & { page: number }) {
`StrictPropsWithChildren & { page: number }`가 반복되어 사용되고 있으므로 `PageWithChildren` 등과 같은 타입을 선언하는게 좋을 것 같아요.

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/components/SubscribeFetcher/types.ts
> +}
동일한 타입이 중복되어 사용되고 있는 것 같아요.

`FollowerListResponse`, `FollowListResponse`는 완전히 동일합니다.

`FollowPostResponse` 내부에 사용되는 타입과 페이지네이션 관련 타입도 완전 동일해요.

페이지네이션 관련 타입은 #36 에 구현되어 있으니 참고하시면 좋을 것 같아요.

2024-05-23 06:43 UTC, Collection50 commented on src/app/subscribe/page.tsx
>        <p className="h-500 w-1 bg-primary mt-100 ml-220 fixed" />
위 `p` 태그 리뷰와 동일합니다.

2024-05-23 09:34 UTC, yeyounging commented on src/app/subscribe/components/Feed/index.tsx
> +  }
서버쪽 에러였는데, 데이터가 없어서 그런 줄 알고 에러처리를 했었습니다요 피드 api 연결하면서 수정할 예정입니다!!

2024-05-23 09:48 UTC, yeyounging commented on src/app/subscribe/components/SubscribeFetcher/types.ts
> +}
> 동일한 타입이 중복되어 사용되고 있는 것 같아요.
> 
> `FollowerListResponse`, `FollowListResponse`는 완전히 동일합니다.
> 
> `FollowPostResponse` 내부에 사용되는 타입과 페이지네이션 관련 타입도 완전 동일해요.
> 
> 페이지네이션 관련 타입은 #36 에 구현되어 있으니 참고하시면 좋을 것 같아요.

wow........ 바보코딩이었네요

2024-05-24 02:38 UTC, Collection50 requested changes
고생하셨습니다 ! 👍 

약간의 변경사항에 대해 코멘트 남겨드렸습니다 !!

2024-05-24 02:38 UTC, Collection50 commented on src/app/subscribe/components/Pagination/index.tsx
> +            <span className="">&gt;</span>
빈 `className`이 할당되고 있어요 !

2024-05-24 02:38 UTC, Collection50 commented on src/app/subscribe/components/Pagination/index.tsx
> +          <span className="">{currentPage + 1}</span>
빈 className이 할당되고 있어요 !

2024-05-24 02:38 UTC, Collection50 commented on src/app/subscribe/components/Pagination/index.tsx
> +            <span className="">&lt;</span>
빈 className이 할당되고 있어요 !

2024-05-24 02:38 UTC, Collection50 commented on src/app/subscribe/components/SubscribeFetcher/index.tsx
> +export function FollowPostFetcher({ children, page }: PageWithChildren) {
훨씬 코드가 깔끔해진 것 같아요 !

2024-05-27 00:51 UTC, Collection50 approved these changes

2024-05-27 00:56 UTC, merged