Glue 258 검색페이지 api 연결
DoTheZ-Team/glue-fe pull request #66
Opened 2024-06-06 19:06 UTC by yeyounging

## 1. 무슨 이유로 코드를 변경했나요?

<br> 검색페이지 api를 연결하였습니다.

## 2. 어떤 위험이나 장애를 발견했나요?

<br> 현재 DTO에 blogId 값이 존재하지 않습니다. 

## 3. 관련 스크린샷을 첨부해주세요.

https://github.com/DoTheZ-Team/glue-fe/assets/133792082/1622c841-6c50-4a20-b1f9-c48dce6d0cc8

## 4. 완료 사항

- [ ] 검색페이지 디자인 수정
- [ ] 네비게이션바 검색창 구현
- [ ] 검색페이지 api 연결
- [ ] 페이지네이션 수정

## 5. 추가 사항

- [ ] DTO 수정 후 검색결과 블로그카드 클릭시 해당 블로그로 라우팅

2024-06-08 09:11 UTC, Collection50 requested changes
고생하셨습니다 !

코드에 대해 코멘트 남겨드렸습니다 !

2024-06-08 09:11 UTC, Collection50 commented on next.config.mjs
> +    domains: ['glue-bucket-2024.s3.ap-northeast-2.amazonaws.com'],
아래 `remotePatterns`가 설정되어있어서 `domains`는 불필요하다고 생각해요.
nextjs 에서 deprecated된 기능으로 알고 있어요.

그리고 이렇게 s3 주소를 git에 적으시면.. 안됩니다... 저희 요금 과금돼요... :flushed:

2024-06-08 09:11 UTC, Collection50 commented on src/api/types.ts
> +}
이 부분은 제가 작성한 pagination 타입을 참조하시면 될것 같아요.

2024-06-08 09:11 UTC, Collection50 commented on src/app/search/components/BlogList/index.tsx
> +              key={generateId()}
`blogInfoList`에 `blogId`를 반환하지 않는 점이 의외네요.
이 부분은 서버 팀원과 얘기해서 변경하는 것도 좋을 것 같아요.
기능에 이상이 없으니 일단 이렇게 둬도 괜찮다고 생각해요 !

2024-06-08 09:11 UTC, Collection50 commented on src/app/search/components/BlogList/index.tsx
> +      />
이 페이지네이션은 제가 생성한 `Pagination` 공통 컴포넌트를 사용하시기 바랍니다 !

2024-06-08 09:11 UTC, Collection50 commented on src/app/search/components/ContentList/index.tsx
> +}: ContentListProps) {
위 페이지네이션 리뷰와 동일해요.

2024-06-08 09:11 UTC, Collection50 commented on src/app/search/components/ContentList/index.tsx
> +      />
위 페이지네이션 리뷰와 동일해요.

2024-06-08 09:11 UTC, Collection50 commented on src/app/search/components/SearchFetcher/SearchContext.tsx
> +    name: 'search-result',
```suggestion
    name: 'search-result-context',
```

위와 같은 네이밍은 어떨까요?

2024-06-08 09:11 UTC, Collection50 commented on src/app/search/page.tsx
> +          )}
`SearchResultFetcher`의 데이터가 필요한 부분은 `ContentList`, `BlogList`이므로 아래와 같이 사용하는게 더 좋을 것 같아요.

```jsx
<SearchResultFetcher page={currentPage} size={10} keyword={query}>
  {postView ? (
    <ContentList currentPage={currentPage} onPageChange={setCurrentPage} />
  ) : (
    <BlogList currentPage={currentPage} onPageChange={setCurrentPage} />
  )}
</SearchResultFetcher>;
```

2024-06-08 09:11 UTC, Collection50 commented on src/app/subscribe/components/Pagination/index.tsx
>            >
공통 페이지네이션 컴포넌트를 사용해주세요 !

2024-06-08 09:11 UTC, Collection50 commented on src/hooks/useSearch.tsx
> +export default useSearch;
함수 선언문 형식으로 작성하는 것이 더 좋을 것 같아요.

현재 `named export`, `default export`가 중복으로 되어 있어요 !

2024-06-08 09:37 UTC, yeyounging commented on next.config.mjs
> +    domains: ['glue-bucket-2024.s3.ap-northeast-2.amazonaws.com'],
> 아래 `remotePatterns`가 설정되어있어서 `domains`는 불필요하다고 생각해요. nextjs 에서 deprecated된 기능으로 알고 있어요.
> 
> 그리고 이렇게 s3 주소를 git에 적으시면.. 안됩니다... 저희 요금 과금돼요... 😳

어라라 . ..  근데 이거 없으면 에러가 나여

2024-06-08 17:42 UTC, Collection50 commented on next.config.mjs
> +    domains: ['glue-bucket-2024.s3.ap-northeast-2.amazonaws.com'],
어떤 에러가 발생하시나요?

2024-06-08 17:44 UTC, Collection50 requested changes
제가 깜빡하고 빠트린 것이 있어서.. 다시 리뷰했습니다 !

2024-06-08 17:44 UTC, Collection50 commented on src/app/search/page.tsx
> +          )}
```jsx
<AsyncBoundaryWithQuery>
  <SearchFallback>
    <SearchResultFetcher page={currentPage} size={10} keyword={query}>
      {postView ? (
        <ContentList currentPage={currentPage} onPageChange={setCurrentPage} />
      ) : (
        <BlogList currentPage={currentPage} onPageChange={setCurrentPage} />
      )}
    </SearchResultFetcher>
  </SearchFallback>
</AsyncBoundaryWithQuery>
```

위와 같은 형식으로 사용하셔야 좋아요 !

2024-06-08 20:04 UTC, yeyounging commented
> 제가 깜빡하고 빠트린 것이 있어서.. 다시 리뷰했습니다 !

늦은 시간 감사합니다아 ~~~~ 반영하고 오류도 수정하였습니당

2024-06-09 05:18 UTC, Collection50 requested changes
고생하셨습니다 !

코드에 대해 간단한 코멘트 남겨드렸습니다 !

2024-06-09 05:18 UTC, Collection50 commented on src/hooks/useSearch.tsx
> +export default useSearch;
여기서도 동일하게 export가 중복되고 있어요 ! 맨 위의 `export`에 `default`를 추가하시고, 아래를 지우면 될 것 같아요 !

2024-06-09 05:18 UTC, Collection50 commented on src/components/Common/NavigationIcons/index.tsx
> +  } = useSearch();
아주 잘 작성하신 것 같아요 ! 👍

2024-06-09 12:49 UTC, yeyounging commented on src/components/Common/NavigationIcons/index.tsx
> +  } = useSearch();
> 아주 잘 작성하신 것 같아요 ! 👍

woow!!!!!!! 😁

2024-06-09 15:33 UTC, Collection50 approved these changes

2024-06-09 17:03 UTC, merged