GLUE-300-로그인정보-전역관리
DoTheZ-Team/glue-fe pull request #70
Opened 2024-06-08 08:16 UTC by yeyounging

## 1. 무슨 이유로 코드를 변경했나요?

<br> 로그인 후 블로그 라우팅을 위해 유저의 블로그id가 필요하여 변경된 DTO 반영 후,   `userId ` 를 전역으로 관리합니다. 

## 2. 어떤 위험이나 장애를 발견했나요?

<br> 

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항

<br> 

- [ ] userContext, userProvider 구현
- [ ] 변경된 DTO 반영

## 5. 추가 사항

<br>

2024-06-08 17:48 UTC, Collection50 requested changes
고생하셨습니다 !

`blogId`에 대한 당위성 부분은 슬랙에 남겨드렸으므로 위 리뷰만 수정하시면 될 것 같아요 !

2024-06-08 17:48 UTC, Collection50 commented on src/components/UserContext/index.tsx
> +  };
`useMemo`를 사용하셔야 해요.

```suggestion
  const contextValue = useMemo(() => ({
    loginId,
    setLoginId,
  }), [loginId, setLoginId]);
```

2024-06-08 17:48 UTC, Collection50 commented on src/components/UserContext/index.tsx
> +export { useUserContext };
이렇게 사용하신 이유가 있나요?? 

다른 파일에서는 아래와 같이 사용하고 있어요 !

```tsx
export const [UserProvider, useUserContext] = generateContext<UserContextProps>({
  name: 'user-info',
});
```

2024-06-08 17:48 UTC, Collection50 commented on src/app/(auth)/auth/api/queries.ts
> +import { useUserContext } from '@/components/UserContext';
`/components/common` 폴더에서 사용하는 것이 좋아보입니다 !

2024-06-08 20:18 UTC, yeyounging commented on src/components/UserContext/index.tsx
> +export { useUserContext };
참고문서를 참조하다보니... 죄송함니다 수정했습니다 !

2024-06-09 05:14 UTC, Collection50 requested changes
고생하셨습니다 !

위 부분만 수정하시면 될 것 같아요 !!

2024-06-09 05:14 UTC, Collection50 commented on src/app/layout.tsx
> +import { UserProviderWrapper } from '@/components/Common/UserContext';
`@/components/Common`의 index 파일에 `UserProviderWrapper`를 추가하시고, 다시 경로를 변경하심이 어떨까요??

2024-06-09 12:32 UTC, yeyounging commented on src/app/layout.tsx
> +import { UserProviderWrapper } from '@/components/Common/UserContext';
앗 죄송함당 ㅜㅜ

2024-06-09 15:34 UTC, Collection50 approved these changes

2024-06-09 17:02 UTC, merged